// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOTCvS5fEoHjoEXiHdbAZ2rQmyGvDc0MY',
    appId: '1:509907481654:web:1fdfa6007df82c192b9497',
    messagingSenderId: '509907481654',
    projectId: 'wealthflow-6c1c9',
    authDomain: 'wealthflow-6c1c9.firebaseapp.com',
    storageBucket: 'wealthflow-6c1c9.firebasestorage.app',
    measurementId: 'G-0LBVD4YZM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2p9lYH2qsJbgPWVtbzdNLdu8vbplIMv0',
    appId: '1:509907481654:android:f2ad299c2b1b90c92b9497',
    messagingSenderId: '509907481654',
    projectId: 'wealthflow-6c1c9',
    storageBucket: 'wealthflow-6c1c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv2kTNKY2t-IFokK8aRqLNu_lucKJiMLs',
    appId: '1:509907481654:ios:d0aca130313c2af42b9497',
    messagingSenderId: '509907481654',
    projectId: 'wealthflow-6c1c9',
    storageBucket: 'wealthflow-6c1c9.firebasestorage.app',
    iosBundleId: 'com.example.wealthflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv2kTNKY2t-IFokK8aRqLNu_lucKJiMLs',
    appId: '1:509907481654:ios:d0aca130313c2af42b9497',
    messagingSenderId: '509907481654',
    projectId: 'wealthflow-6c1c9',
    storageBucket: 'wealthflow-6c1c9.firebasestorage.app',
    iosBundleId: 'com.example.wealthflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOTCvS5fEoHjoEXiHdbAZ2rQmyGvDc0MY',
    appId: '1:509907481654:web:bc06cac68708e21d2b9497',
    messagingSenderId: '509907481654',
    projectId: 'wealthflow-6c1c9',
    authDomain: 'wealthflow-6c1c9.firebaseapp.com',
    storageBucket: 'wealthflow-6c1c9.firebasestorage.app',
    measurementId: 'G-3KWC5LE5JX',
  );
}
